name: Build and Deploy API Server

on:
  # Triggers the workflow on push events but only for the main branch and release tag
  push:
    branches: [main]
    tags:
      # Regex for a version number such as 0.2.1
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

env:
  BINARY_NAME: ntex-restful-api-server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: cargo build --verbose --release
